language: python
python: 2.7
env:
  - PLONE_VERSION=4.3
install:
  - sed -i "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/test
  - test -v QA && bin/code-analysis || true
after_success: test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
after_failure:
  - bin/buildout annotate -c travis.cfg
  - firefox -v
notifications:
  irc: irc.freenode.org#plonegovbr
